name: Update Results Data

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow every day at midnight UTC
  workflow_dispatch:

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt file with your dependencies
    - name: check for changes
      run: git status
    - name: Run update script
      env: 
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: python fetch_data.py  # Replace with the path to your Python script
    - name: check for changes
      run: git status
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add _data/*
        if git diff --quiet; then
          echo "No changes to commit."
        else
          git commit -m 'Update results data'
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
